### ISSUE TITLE
No relevant error information

### ISSUE THREAD

**Issue by jonsgold** [stoplightio/spectral-action#221]
**Summary**
Show the exact error that caused the action failure

**Example**
All it says is '1 issue detected':
![image](https://user-images.githubusercontent.com/5622533/83355481-67b40a00-a368-11ea-965f-4c9c3b0f2fa1.png)

When I run the linter locally, I get `error  oas3-schema  'requestBody' property should have required property '$ref'`. This is an issue in of itself that I documented here: https://github.com/stoplightio/spectral/issues/1072#issuecomment-636482005.

**Comment by XVincentX** [comment]
You should be able to see the error details through the GitHub check UI. These you're looking at are just logs and not really meant for user consumption.
