### ISSUE TITLE
Master is broken, the action does not run

### ISSUE THREAD

**Issue by apeacock1991** [stoplightio/spectral-action#294]
## Describe the bug

Master looks [broken](https://github.com/stoplightio/spectral-action/actions/runs/208843869) as it does not run the Spectral checks (even though the checks themselves show ticks in the Actions view)

## To Reproduce

Run the GitHub action (see https://github.com/stoplightio/spectral-action/actions/runs/208843869). Just using the default config, the action does not run.

The error is:

```
required property "after"
└─ cannot decode undefined, should be string
```

## Expected behavior

The GitHub action should run the Spectral checks.

**Comment by shavo007** [comment]
I am getting this issue also. Was this resolved?

https://github.com/shavo007/docker-kong/runs/1653502328?check_suite_focus=true

https://github.com/shavo007/docker-kong/blob/main/.github/workflows/main.yml

**Comment by XVincentX** [comment]
It seems like something has changed in the GitHub expected payload. We can try to take a look into

**Comment by mh-spillai** [comment]
Still, I'm getting this issue do I need to file a new ticket

**Comment by shavo007** [comment]
or can we reopen this issue?

**Comment by mh-spillai** [comment]
> or can we reopen this issue?

that will be better. this issue is happening only when a pull request is created when the pull request is updated spectral linter working fine.

**Comment by mh-spillai** [comment]
> or can we reopen this issue?

I have created new issue 
https://github.com/stoplightio/spectral-action/issues/443
