### ISSUE TITLE
When a pull request is created spectral linter is not working

### ISSUE THREAD

**Issue by mh-spillai** [stoplightio/spectral-action#443]
## Describe the bug

When a pull request is created spectral linter is not working. showing the following error.

"required property "after" └─ cannot decode undefined, should be string"

its works fine when the pull request is updated with a new push.

## To Reproduce
Workflow File:-
[workflow file.zip](https://github.com/stoplightio/spectral-action/files/5950349/workflow.file.zip)

## Expected behaviour

Spectral linter should work when the pull request is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/75423468/107345160-4f94ad00-6ae9-11eb-8df8-16e52490a119.png)

**Comment by mh-spillai** [comment]
@philsturgeon could you please look into this issue

**Comment by andreas-zapantis** [comment]
For me it seems to be failing even after creation in a random way. Using stoplightio/spectral-action@v0.7.0

**Comment by mh-spillai** [comment]
We are using spectral lint for our CI process. So this is a blocker for us.

Can anyone please look into this issue.?

**Comment by mnaumanali94** [comment]
Fixed in v0.7.1

**Comment by mh-spillai** [comment]
Now it's working fine. Thank You, Guys.
