### ISSUE TITLE
Extra job "Lint (push)" remains in progress

### ISSUE THREAD

**Issue by andreas-zapantis** [stoplightio/spectral-action#506]
## Describe the bug

Using this action we get an extra job named "Lint (push)" that never completes. This marks checks on PRs as not completed.  See also screenshot
![image](https://user-images.githubusercontent.com/73124559/114561193-0510e780-9c76-11eb-99dc-408de5c4da6a.png)

Along with our defined job "Run Spectral" an extra job "Lint (push)" appears on builds that never completes.

## To Reproduce

We use the same configuration that's included in project readme. 

**Environment (remove any that are not applicable):**
 - Library version: 0.7.0 and 0.7.1

**Comment by mh-spillai** [comment]
Me also facing the same issue can you guys please fix this ASAP @mnaumanali94 @P0lip

**Comment by domagojk** [comment]
This should be fixed in `v0.7.3`. Please reopen it if you find any issues with it!

**Comment by hyorimitsu** [comment]
I am facing the same issue in `v0.8.1`.

**Comment by hyorimitsu** [comment]
I am facing the same issue in `v0.8.1`. @domagojk

**Comment by hyorimitsu** [comment]
I am facing the same issue in `v0.8.1`.
I want to cancel `Lint(push)` job that has already been started, is there any way to do this?

**Comment by ahmedbodi** [comment]
This looks to have been re-introduced
