### ISSUE TITLE
Recent builds using action failing trying to build docker image

### ISSUE THREAD

**Issue by andreas-zapantis** [stoplightio/spectral-action#634]
Today we started getting failures in our github actions builds using this action.
Failure encountered during the `Build stoplightio/spectral-action@v0.8.1` step with the following message 
```
Step 12/19 : RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash
   ---> Using cache
   ---> 5dbcc9210831
  Step 13/19 : RUN ./bin/node-prune
   ---> Running in 1629fd948d2e
  /bin/sh: 1: ./bin/node-prune: not found
  The command '/bin/sh -c ./bin/node-prune' returned a non-zero code: 127
```
Seems like `https://install.goreleaser.com/github.com/tj/node-prune.sh` is not accessible anymore.

- Version used: 0.8.1

**Comment by ckoegel** [comment]
Also seeing this on 0.7.3

**Comment by machisuke** [comment]
Maybe https://github.com/stoplightio/spectral-action/pull/633 would fix this issue.

**Comment by P0lip** [comment]
Should be fixed. LMK if you still face the issue
